// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | MultiColumnFooterSlice
  | MediaSideIntroSlice
  | CtaHeroBannerSlice
  | MilestoneTimelineSlice
  | MilestoneHighlightsSlice
  | TimelineHighlightsSlice
  | TimelineGridSlice
  | FeaturedUpdatesSlice
  | CoreTeamGridSlice
  | VisualTextSplitSlice
  | TwoColumnImageTextIntroSlice
  | SideBySideFeatureListSlice
  | IconBulletlistIntroSlice
  | FeatureColumnsIntroSlice
  | HeadlineDescriptionGraphCtaSlice
  | IconHeadlineColumnsSlice
  | HeadlineCtaImageSlice
  | HeaderNavigationSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

export type AllDocumentTypes = HomepageDocument;

/**
 * Item in *CoreTeamGrid → Default → Primary → Team Members*
 */
export interface CoreTeamGridSliceDefaultPrimaryMembersItem {
  /**
   * Photo field in *CoreTeamGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.members[].photo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  photo: prismic.ImageField<never>;

  /**
   * Name field in *CoreTeamGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.members[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *CoreTeamGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.members[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Bio field in *CoreTeamGrid → Default → Primary → Team Members*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.members[].bio
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;
}

/**
 * Primary content in *CoreTeamGrid → Default → Primary*
 */
export interface CoreTeamGridSliceDefaultPrimary {
  /**
   * Section Title field in *CoreTeamGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Section Description field in *CoreTeamGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Team Members field in *CoreTeamGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: core_team_grid.default.primary.members[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  members: prismic.GroupField<
    Simplify<CoreTeamGridSliceDefaultPrimaryMembersItem>
  >;
}

/**
 * Default variation for CoreTeamGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout for displaying multiple core team members in a grid, along with section heading and description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreTeamGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoreTeamGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CoreTeamGrid*
 */
type CoreTeamGridSliceVariation = CoreTeamGridSliceDefault;

/**
 * CoreTeamGrid Shared Slice
 *
 * - **API ID**: `core_team_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CoreTeamGridSlice = prismic.SharedSlice<
  "core_team_grid",
  CoreTeamGridSliceVariation
>;

/**
 * Primary content in *CtaHeroBanner → Default → Primary*
 */
export interface CtaHeroBannerSliceDefaultPrimary {
  /**
   * Eyebrow field in *CtaHeroBanner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_hero_banner.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Title field in *CtaHeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_hero_banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *CtaHeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_hero_banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA field in *CtaHeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_hero_banner.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA field in *CtaHeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_hero_banner.default.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CtaHeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Supports headline, eyebrow, description, and a primary and secondary call-to-action.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaHeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaHeroBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaHeroBanner*
 */
type CtaHeroBannerSliceVariation = CtaHeroBannerSliceDefault;

/**
 * CtaHeroBanner Shared Slice
 *
 * - **API ID**: `cta_hero_banner`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaHeroBannerSlice = prismic.SharedSlice<
  "cta_hero_banner",
  CtaHeroBannerSliceVariation
>;

/**
 * Item in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary → Features*
 */
export interface FeatureColumnsIntroSliceHeadingText3ColumnFeaturePrimaryFeaturesItem {
  /**
   * Icon Name or Identifier field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary → Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  icon: prismic.KeyTextField;

  /**
   * Feature Title field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.features[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Feature Description field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary → Features*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.features[].feature_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  feature_description: prismic.RichTextField;
}

/**
 * Primary content in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary*
 */
export interface FeatureColumnsIntroSliceHeadingText3ColumnFeaturePrimary {
  /**
   * Eyebrow (Small Section Title) field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Features field in *FeatureColumnsIntro → Heading, Description, 3 Feature Columns → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: feature_columns_intro.heading_text_3_column_feature.primary.features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  features: prismic.GroupField<
    Simplify<FeatureColumnsIntroSliceHeadingText3ColumnFeaturePrimaryFeaturesItem>
  >;
}

/**
 * Heading, Description, 3 Feature Columns variation for FeatureColumnsIntro Slice
 *
 * - **API ID**: `heading_text_3_column_feature`
 * - **Description**: This variation includes a small intro title, large heading, brief description, and three visually separate feature columns, each with a heading and description. Optionally, each feature can have an associated icon.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureColumnsIntroSliceHeadingText3ColumnFeature =
  prismic.SharedSliceVariation<
    "heading_text_3_column_feature",
    Simplify<FeatureColumnsIntroSliceHeadingText3ColumnFeaturePrimary>,
    never
  >;

/**
 * Slice variation for *FeatureColumnsIntro*
 */
type FeatureColumnsIntroSliceVariation =
  FeatureColumnsIntroSliceHeadingText3ColumnFeature;

/**
 * FeatureColumnsIntro Shared Slice
 *
 * - **API ID**: `feature_columns_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeatureColumnsIntroSlice = prismic.SharedSlice<
  "feature_columns_intro",
  FeatureColumnsIntroSliceVariation
>;

/**
 * Item in *FeaturedUpdates → Default → Primary → Updates*
 */
export interface FeaturedUpdatesSliceDefaultPrimaryUpdatesItem {
  /**
   * Date Label field in *FeaturedUpdates → Default → Primary → Updates*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.updates[].date_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_label: prismic.KeyTextField;

  /**
   * Title field in *FeaturedUpdates → Default → Primary → Updates*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.updates[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FeaturedUpdates → Default → Primary → Updates*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.updates[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Attribution field in *FeaturedUpdates → Default → Primary → Updates*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.updates[].attribution
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  attribution: prismic.KeyTextField;

  /**
   * External Link field in *FeaturedUpdates → Default → Primary → Updates*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.updates[].external_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  external_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *FeaturedUpdates → Default → Primary*
 */
export interface FeaturedUpdatesSliceDefaultPrimary {
  /**
   * Section Heading field in *FeaturedUpdates → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Section Description field in *FeaturedUpdates → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Updates field in *FeaturedUpdates → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_updates.default.primary.updates[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  updates: prismic.GroupField<
    Simplify<FeaturedUpdatesSliceDefaultPrimaryUpdatesItem>
  >;
}

/**
 * Default variation for FeaturedUpdates Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays updates in a two-column layout, each featuring a date, headline, description, author/attribution, and an optional external link icon button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedUpdatesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedUpdatesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedUpdates*
 */
type FeaturedUpdatesSliceVariation = FeaturedUpdatesSliceDefault;

/**
 * FeaturedUpdates Shared Slice
 *
 * - **API ID**: `featured_updates`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedUpdatesSlice = prismic.SharedSlice<
  "featured_updates",
  FeaturedUpdatesSliceVariation
>;

/**
 * Item in *HeaderNavigation → Default → Primary → Navigation Links*
 */
export interface HeaderNavigationSliceDefaultPrimaryNavLinksItem {
  /**
   * Label field in *HeaderNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *HeaderNavigation → Default → Primary → Navigation Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *HeaderNavigation → Default → Primary*
 */
export interface HeaderNavigationSliceDefaultPrimary {
  /**
   * Logo field in *HeaderNavigation → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation Links field in *HeaderNavigation → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.nav_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  nav_links: prismic.GroupField<
    Simplify<HeaderNavigationSliceDefaultPrimaryNavLinksItem>
  >;

  /**
   * CTA Button field in *HeaderNavigation → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header_navigation.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeaderNavigation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard header with logo, horizontal menu links, and a single highlighted CTA button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderNavigationSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderNavigationSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeaderNavigation*
 */
type HeaderNavigationSliceVariation = HeaderNavigationSliceDefault;

/**
 * HeaderNavigation Shared Slice
 *
 * - **API ID**: `header_navigation`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeaderNavigationSlice = prismic.SharedSlice<
  "header_navigation",
  HeaderNavigationSliceVariation
>;

/**
 * Primary content in *HeroBanner → Default → Primary*
 */
export interface HeadlineCtaImageSliceDefaultPrimary {
  /**
   * Eyebrow / Intro Line field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_image.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow: prismic.RichTextField;

  /**
   * Headline field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_image.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Emphasized Text field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_image.default.primary.emphasized_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  emphasized_text: prismic.RichTextField;

  /**
   * Description field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_image.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA Button field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_image.default.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Main Image field in *HeroBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_cta_image.default.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: The standard layout featuring headline, subheading, descriptive text, call to action, and supportive image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineCtaImageSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadlineCtaImageSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeadlineCtaImageSliceVariation = HeadlineCtaImageSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `headline_cta_image`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineCtaImageSlice = prismic.SharedSlice<
  "headline_cta_image",
  HeadlineCtaImageSliceVariation
>;

/**
 * Item in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Metrics List*
 */
export interface HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimaryMetricsListItem {
  /**
   * Metric Label field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Metrics List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metrics_list[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Metric Value field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Metrics List*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metrics_list[].value
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  value: prismic.NumberField;

  /**
   * Metric Unit field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Metrics List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metrics_list[].unit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  unit: prismic.KeyTextField;

  /**
   * Style field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Metrics List*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metrics_list[].style
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  style: prismic.SelectField<"default" | "critical" | "highlighted">;
}

/**
 * Item in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Tag List*
 */
export interface HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimaryTagListItem {
  /**
   * Tag Label field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Tag List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.tag_list[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Color Scheme field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary → Tag List*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.tag_list[].color_scheme
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  color_scheme: prismic.SelectField<"default" | "positive" | "warning">;
}

/**
 * Primary content in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
 */
export interface HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimary {
  /**
   * Eyebrow field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow: prismic.RichTextField;

  /**
   * Headline field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Highlighted Phrase field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.highlighted_phrase
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlighted_phrase: prismic.RichTextField;

  /**
   * Description field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Primary CTA field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.primary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  primary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Secondary CTA field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.secondary_cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  secondary_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Metric Visualization Image field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metric_visualization_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  metric_visualization_image: prismic.ImageField<never>;

  /**
   * Metric Title field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metric_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  metric_title: prismic.RichTextField;

  /**
   * Metrics List field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.metrics_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  metrics_list: prismic.GroupField<
    Simplify<HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimaryMetricsListItem>
  >;

  /**
   * Tag List field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.tag_list[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  tag_list: prismic.GroupField<
    Simplify<HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimaryTagListItem>
  >;

  /**
   * Recommendation Text field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.recommendation_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  recommendation_text: prismic.RichTextField;

  /**
   * Note field in *HeadlineDescriptionGraphCta → Left Text, Right Metric Card → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: headline_description_graph_cta.default_left_text_right_metric.primary.note
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  note: prismic.KeyTextField;
}

/**
 * Left Text, Right Metric Card variation for HeadlineDescriptionGraphCta Slice
 *
 * - **API ID**: `default_left_text_right_metric`
 * - **Description**: Displays headline, subheadline, description, and two CTAs on the left, and a comprehensive metric/data visualization card with tags and recommendations on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetric =
  prismic.SharedSliceVariation<
    "default_left_text_right_metric",
    Simplify<HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimary>,
    never
  >;

/**
 * Slice variation for *HeadlineDescriptionGraphCta*
 */
type HeadlineDescriptionGraphCtaSliceVariation =
  HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetric;

/**
 * HeadlineDescriptionGraphCta Shared Slice
 *
 * - **API ID**: `headline_description_graph_cta`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeadlineDescriptionGraphCtaSlice = prismic.SharedSlice<
  "headline_description_graph_cta",
  HeadlineDescriptionGraphCtaSliceVariation
>;

/**
 * Item in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary → Bullet Items*
 */
export interface IconBulletlistIntroSliceIntroWithIconBulletlistPrimaryItemsItem {
  /**
   * Icon field in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary → Bullet Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_bulletlist_intro.intro_with_icon_bulletlist.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Item Title field in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary → Bullet Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_bulletlist_intro.intro_with_icon_bulletlist.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Item Description field in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary → Bullet Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_bulletlist_intro.intro_with_icon_bulletlist.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary*
 */
export interface IconBulletlistIntroSliceIntroWithIconBulletlistPrimary {
  /**
   * Intro Text field in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_bulletlist_intro.intro_with_icon_bulletlist.primary.intro_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro_text: prismic.RichTextField;

  /**
   * Bullet Items field in *IconBulletlistIntro → Intro with Icon Bulletlist → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_bulletlist_intro.intro_with_icon_bulletlist.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<IconBulletlistIntroSliceIntroWithIconBulletlistPrimaryItemsItem>
  >;
}

/**
 * Intro with Icon Bulletlist variation for IconBulletlistIntro Slice
 *
 * - **API ID**: `intro_with_icon_bulletlist`
 * - **Description**: Displays a short intro/heading followed by a bullet list, where each item has an icon, a title, and a description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconBulletlistIntroSliceIntroWithIconBulletlist =
  prismic.SharedSliceVariation<
    "intro_with_icon_bulletlist",
    Simplify<IconBulletlistIntroSliceIntroWithIconBulletlistPrimary>,
    never
  >;

/**
 * Slice variation for *IconBulletlistIntro*
 */
type IconBulletlistIntroSliceVariation =
  IconBulletlistIntroSliceIntroWithIconBulletlist;

/**
 * IconBulletlistIntro Shared Slice
 *
 * - **API ID**: `icon_bulletlist_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconBulletlistIntroSlice = prismic.SharedSlice<
  "icon_bulletlist_intro",
  IconBulletlistIntroSliceVariation
>;

/**
 * Item in *IconHeadlineColumns → Default → Primary → Items*
 */
export interface IconHeadlineColumnsSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *IconHeadlineColumns → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_headline_columns.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Headline field in *IconHeadlineColumns → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_headline_columns.default.primary.items[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Subheadline field in *IconHeadlineColumns → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_headline_columns.default.primary.items[].subheadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subheadline: prismic.KeyTextField;

  /**
   * Description field in *IconHeadlineColumns → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_headline_columns.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *IconHeadlineColumns → Default → Primary*
 */
export interface IconHeadlineColumnsSliceDefaultPrimary {
  /**
   * Items field in *IconHeadlineColumns → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_headline_columns.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<IconHeadlineColumnsSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for IconHeadlineColumns Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays 2-6 columns with consistent structure: icon, bold heading, supporting headline, and smaller description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconHeadlineColumnsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconHeadlineColumnsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconHeadlineColumns*
 */
type IconHeadlineColumnsSliceVariation = IconHeadlineColumnsSliceDefault;

/**
 * IconHeadlineColumns Shared Slice
 *
 * - **API ID**: `icon_headline_columns`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type IconHeadlineColumnsSlice = prismic.SharedSlice<
  "icon_headline_columns",
  IconHeadlineColumnsSliceVariation
>;

/**
 * Primary content in *MediaSideIntro → Logo Left, Text Right → Primary*
 */
export interface MediaSideIntroSliceLogoLeftTextRightPrimary {
  /**
   * Logo or Media field in *MediaSideIntro → Logo Left, Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_side_intro.logo_left_text_right.primary.media
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  media: prismic.ImageField<never>;

  /**
   * Title field in *MediaSideIntro → Logo Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_side_intro.logo_left_text_right.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *MediaSideIntro → Logo Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_side_intro.logo_left_text_right.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Logo Left, Text Right variation for MediaSideIntro Slice
 *
 * - **API ID**: `logo_left_text_right`
 * - **Description**: Displays a logo or media element on the left and textual intro (headline, description) on the right. Common for hero or about areas with branding.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSideIntroSliceLogoLeftTextRight = prismic.SharedSliceVariation<
  "logo_left_text_right",
  Simplify<MediaSideIntroSliceLogoLeftTextRightPrimary>,
  never
>;

/**
 * Slice variation for *MediaSideIntro*
 */
type MediaSideIntroSliceVariation = MediaSideIntroSliceLogoLeftTextRight;

/**
 * MediaSideIntro Shared Slice
 *
 * - **API ID**: `media_side_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSideIntroSlice = prismic.SharedSlice<
  "media_side_intro",
  MediaSideIntroSliceVariation
>;

/**
 * Item in *MilestoneHighlights → Default → Primary → Milestones*
 */
export interface MilestoneHighlightsSliceDefaultPrimaryMilestonesItem {
  /**
   * Date field in *MilestoneHighlights → Default → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.milestones[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Title field in *MilestoneHighlights → Default → Primary → Milestones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.milestones[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Milestone Description field in *MilestoneHighlights → Default → Primary → Milestones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.milestones[].milestone_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  milestone_description: prismic.RichTextField;

  /**
   * Author field in *MilestoneHighlights → Default → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.milestones[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * Action Link field in *MilestoneHighlights → Default → Primary → Milestones*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.milestones[].action_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  action_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *MilestoneHighlights → Default → Primary*
 */
export interface MilestoneHighlightsSliceDefaultPrimary {
  /**
   * Headline field in *MilestoneHighlights → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  headline: prismic.RichTextField;

  /**
   * Description field in *MilestoneHighlights → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Milestones field in *MilestoneHighlights → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_highlights.default.primary.milestones[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  milestones: prismic.GroupField<
    Simplify<MilestoneHighlightsSliceDefaultPrimaryMilestonesItem>
  >;
}

/**
 * Default variation for MilestoneHighlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Horizontally-arranged milestone cards under a heading, each with a date, title, description, author, and action button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MilestoneHighlightsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MilestoneHighlightsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *MilestoneHighlights*
 */
type MilestoneHighlightsSliceVariation = MilestoneHighlightsSliceDefault;

/**
 * MilestoneHighlights Shared Slice
 *
 * - **API ID**: `milestone_highlights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MilestoneHighlightsSlice = prismic.SharedSlice<
  "milestone_highlights",
  MilestoneHighlightsSliceVariation
>;

/**
 * Item in *MilestoneTimeline → Simple Two Column → Primary → Milestones*
 */
export interface MilestoneTimelineSliceSimpleTwoColumnPrimaryMilestonesItem {
  /**
   * Milestone Date field in *MilestoneTimeline → Simple Two Column → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.milestones[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Title field in *MilestoneTimeline → Simple Two Column → Primary → Milestones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.milestones[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *MilestoneTimeline → Simple Two Column → Primary → Milestones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.milestones[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Attribution field in *MilestoneTimeline → Simple Two Column → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.milestones[].attribution
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  attribution: prismic.KeyTextField;

  /**
   * External Link field in *MilestoneTimeline → Simple Two Column → Primary → Milestones*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.milestones[].external_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  external_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *MilestoneTimeline → Simple Two Column → Primary*
 */
export interface MilestoneTimelineSliceSimpleTwoColumnPrimary {
  /**
   * Section Heading field in *MilestoneTimeline → Simple Two Column → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Section Subheading field in *MilestoneTimeline → Simple Two Column → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.section_subheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_subheading: prismic.RichTextField;

  /**
   * Milestones field in *MilestoneTimeline → Simple Two Column → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: milestone_timeline.simple_two_column.primary.milestones[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  milestones: prismic.GroupField<
    Simplify<MilestoneTimelineSliceSimpleTwoColumnPrimaryMilestonesItem>
  >;
}

/**
 * Simple Two Column variation for MilestoneTimeline Slice
 *
 * - **API ID**: `simple_two_column`
 * - **Description**: Milestones are displayed in two columns with date, title, description, attribution, and an optional link icon for each item.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MilestoneTimelineSliceSimpleTwoColumn =
  prismic.SharedSliceVariation<
    "simple_two_column",
    Simplify<MilestoneTimelineSliceSimpleTwoColumnPrimary>,
    never
  >;

/**
 * Slice variation for *MilestoneTimeline*
 */
type MilestoneTimelineSliceVariation = MilestoneTimelineSliceSimpleTwoColumn;

/**
 * MilestoneTimeline Shared Slice
 *
 * - **API ID**: `milestone_timeline`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MilestoneTimelineSlice = prismic.SharedSlice<
  "milestone_timeline",
  MilestoneTimelineSliceVariation
>;

/**
 * Item in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
 */
export interface MultiColumnFooterSliceStandardPrimaryColumnsItem {
  /**
   * Column Type field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].type
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  type: prismic.SelectField<
    | "contact_info"
    | "navigation_links"
    | "social_links"
    | "newsletter_signup"
    | "custom"
  >;

  /**
   * Column Heading field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Address field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].address
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  address: prismic.KeyTextField;

  /**
   * Secondary Contact Info field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].secondary_contact
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  secondary_contact: prismic.KeyTextField;

  /**
   * Social Icons field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].social_icons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_icons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "facebook" | "twitter" | "instagram" | "youtube" | "linkedin"
    >
  >;

  /**
   * Custom Links Heading field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].custom_links_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  custom_links_heading: prismic.RichTextField;

  /**
   * Custom Link Label field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].custom_link_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  custom_link_label: prismic.KeyTextField;

  /**
   * Custom Links field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].custom_links
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  custom_links: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Newsletter Text field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].newsletter_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  newsletter_text: prismic.RichTextField;

  /**
   * Email Field Placeholder field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].email_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email_placeholder: prismic.KeyTextField;

  /**
   * Submit Button Label field in *MultiColumnFooter → Standard Multi-Column Footer → Primary → Footer Columns*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[].submit_button_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_label: prismic.KeyTextField;
}

/**
 * Primary content in *MultiColumnFooter → Standard Multi-Column Footer → Primary*
 */
export interface MultiColumnFooterSliceStandardPrimary {
  /**
   * Footer Columns field in *MultiColumnFooter → Standard Multi-Column Footer → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: multi_column_footer.standard.primary.columns[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  columns: prismic.GroupField<
    Simplify<MultiColumnFooterSliceStandardPrimaryColumnsItem>
  >;
}

/**
 * Standard Multi-Column Footer variation for MultiColumnFooter Slice
 *
 * - **API ID**: `standard`
 * - **Description**: Footer layout with four columns: Contact Info, Platform Links, Social Ecosystem, and Newsletter Signup. Includes group fields for links and social icons, and a form field for email subscription.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MultiColumnFooterSliceStandard = prismic.SharedSliceVariation<
  "standard",
  Simplify<MultiColumnFooterSliceStandardPrimary>,
  never
>;

/**
 * Slice variation for *MultiColumnFooter*
 */
type MultiColumnFooterSliceVariation = MultiColumnFooterSliceStandard;

/**
 * MultiColumnFooter Shared Slice
 *
 * - **API ID**: `multi_column_footer`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MultiColumnFooterSlice = prismic.SharedSlice<
  "multi_column_footer",
  MultiColumnFooterSliceVariation
>;

/**
 * Item in *SideBySideFeatureList → Default → Primary → Feature Groups*
 */
export interface SideBySideFeatureListSliceDefaultPrimaryFeatureGroupsItem {
  /**
   * Group Heading field in *SideBySideFeatureList → Default → Primary → Feature Groups*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.feature_groups[].group_heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  group_heading: prismic.KeyTextField;

  /**
   * Features field in *SideBySideFeatureList → Default → Primary → Feature Groups*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.feature_groups[].features
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  features: prismic.RichTextField;
}

/**
 * Primary content in *SideBySideFeatureList → Default → Primary*
 */
export interface SideBySideFeatureListSliceDefaultPrimary {
  /**
   * Subtitle field in *SideBySideFeatureList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Title field in *SideBySideFeatureList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *SideBySideFeatureList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Feature Groups field in *SideBySideFeatureList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.feature_groups[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  feature_groups: prismic.GroupField<
    Simplify<SideBySideFeatureListSliceDefaultPrimaryFeatureGroupsItem>
  >;

  /**
   * Highlighted Text field in *SideBySideFeatureList → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: side_by_side_feature_list.default.primary.highlighted_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlighted_text: prismic.RichTextField;
}

/**
 * Default variation for SideBySideFeatureList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard layout with two adjacent feature groups and a highlighted section underneath.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideBySideFeatureListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SideBySideFeatureListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SideBySideFeatureList*
 */
type SideBySideFeatureListSliceVariation = SideBySideFeatureListSliceDefault;

/**
 * SideBySideFeatureList Shared Slice
 *
 * - **API ID**: `side_by_side_feature_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SideBySideFeatureListSlice = prismic.SharedSlice<
  "side_by_side_feature_list",
  SideBySideFeatureListSliceVariation
>;

/**
 * Item in *TimelineGrid → 3-Column Simple Timeline → Primary → Timeline Items*
 */
export interface TimelineGridSliceThreeColumnSimplePrimaryTimelineItemsItem {
  /**
   * Date Label field in *TimelineGrid → 3-Column Simple Timeline → Primary → Timeline Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_grid.three_column_simple.primary.timeline_items[].date_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_label: prismic.KeyTextField;

  /**
   * Event Title field in *TimelineGrid → 3-Column Simple Timeline → Primary → Timeline Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_grid.three_column_simple.primary.timeline_items[].event_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_title: prismic.RichTextField;

  /**
   * Event Description field in *TimelineGrid → 3-Column Simple Timeline → Primary → Timeline Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_grid.three_column_simple.primary.timeline_items[].event_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  event_description: prismic.RichTextField;
}

/**
 * Primary content in *TimelineGrid → 3-Column Simple Timeline → Primary*
 */
export interface TimelineGridSliceThreeColumnSimplePrimary {
  /**
   * Section Heading field in *TimelineGrid → 3-Column Simple Timeline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_grid.three_column_simple.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Section Description field in *TimelineGrid → 3-Column Simple Timeline → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_grid.three_column_simple.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Timeline Items field in *TimelineGrid → 3-Column Simple Timeline → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_grid.three_column_simple.primary.timeline_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  timeline_items: prismic.GroupField<
    Simplify<TimelineGridSliceThreeColumnSimplePrimaryTimelineItemsItem>
  >;
}

/**
 * 3-Column Simple Timeline variation for TimelineGrid Slice
 *
 * - **API ID**: `three_column_simple`
 * - **Description**: Displays timeline events in a three-column grid layout. Each event includes a date, title, and description. Supports unordered lists for additional sub-events or highlights in the description.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineGridSliceThreeColumnSimple = prismic.SharedSliceVariation<
  "three_column_simple",
  Simplify<TimelineGridSliceThreeColumnSimplePrimary>,
  never
>;

/**
 * Slice variation for *TimelineGrid*
 */
type TimelineGridSliceVariation = TimelineGridSliceThreeColumnSimple;

/**
 * TimelineGrid Shared Slice
 *
 * - **API ID**: `timeline_grid`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineGridSlice = prismic.SharedSlice<
  "timeline_grid",
  TimelineGridSliceVariation
>;

/**
 * Item in *TimelineHighlights → Two Column Events → Primary → Milestones*
 */
export interface TimelineHighlightsSliceTwoColumnEventsPrimaryMilestonesItem {
  /**
   * Date field in *TimelineHighlights → Two Column Events → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.milestones[].date
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date: prismic.KeyTextField;

  /**
   * Milestone Title field in *TimelineHighlights → Two Column Events → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.milestones[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Milestone Description field in *TimelineHighlights → Two Column Events → Primary → Milestones*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.milestones[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Milestone Author field in *TimelineHighlights → Two Column Events → Primary → Milestones*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.milestones[].author
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  author: prismic.KeyTextField;

  /**
   * LinkedIn Button field in *TimelineHighlights → Two Column Events → Primary → Milestones*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.milestones[].linkedin_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *TimelineHighlights → Two Column Events → Primary*
 */
export interface TimelineHighlightsSliceTwoColumnEventsPrimary {
  /**
   * Section Title field in *TimelineHighlights → Two Column Events → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_title: prismic.RichTextField;

  /**
   * Section Description field in *TimelineHighlights → Two Column Events → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Milestones field in *TimelineHighlights → Two Column Events → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: timeline_highlights.two_column_events.primary.milestones[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  milestones: prismic.GroupField<
    Simplify<TimelineHighlightsSliceTwoColumnEventsPrimaryMilestonesItem>
  >;
}

/**
 * Two Column Events variation for TimelineHighlights Slice
 *
 * - **API ID**: `two_column_events`
 * - **Description**: Events are arranged in two columns, each showing date, title, description, author, and a LinkedIn button.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineHighlightsSliceTwoColumnEvents =
  prismic.SharedSliceVariation<
    "two_column_events",
    Simplify<TimelineHighlightsSliceTwoColumnEventsPrimary>,
    never
  >;

/**
 * Slice variation for *TimelineHighlights*
 */
type TimelineHighlightsSliceVariation = TimelineHighlightsSliceTwoColumnEvents;

/**
 * TimelineHighlights Shared Slice
 *
 * - **API ID**: `timeline_highlights`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TimelineHighlightsSlice = prismic.SharedSlice<
  "timeline_highlights",
  TimelineHighlightsSliceVariation
>;

/**
 * Primary content in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
 */
export interface TwoColumnImageTextIntroSliceImageLeftTextRightIntroPrimary {
  /**
   * Eyebrow field in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_image_text_intro.image_left_text_right_intro.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  eyebrow: prismic.RichTextField;

  /**
   * Title field in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_image_text_intro.image_left_text_right_intro.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Highlighted Text field in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_image_text_intro.image_left_text_right_intro.primary.highlighted_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  highlighted_text: prismic.RichTextField;

  /**
   * Main Image field in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_image_text_intro.image_left_text_right_intro.primary.main_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Right Title (Bolded) field in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_image_text_intro.image_left_text_right_intro.primary.right_title_intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  right_title_intro: prismic.RichTextField;

  /**
   * Description field in *TwoColumnImageTextIntro → Image Left, Text Right Intro → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_column_image_text_intro.image_left_text_right_intro.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Image Left, Text Right Intro variation for TwoColumnImageTextIntro Slice
 *
 * - **API ID**: `image_left_text_right_intro`
 * - **Description**: A two-column section with an image on the left and a title, highlighted text, and description content on the right. Ideal for introductory or feature highlight sections.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnImageTextIntroSliceImageLeftTextRightIntro =
  prismic.SharedSliceVariation<
    "image_left_text_right_intro",
    Simplify<TwoColumnImageTextIntroSliceImageLeftTextRightIntroPrimary>,
    never
  >;

/**
 * Slice variation for *TwoColumnImageTextIntro*
 */
type TwoColumnImageTextIntroSliceVariation =
  TwoColumnImageTextIntroSliceImageLeftTextRightIntro;

/**
 * TwoColumnImageTextIntro Shared Slice
 *
 * - **API ID**: `two_column_image_text_intro`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TwoColumnImageTextIntroSlice = prismic.SharedSlice<
  "two_column_image_text_intro",
  TwoColumnImageTextIntroSliceVariation
>;

/**
 * Primary content in *VisualTextSplit → Image Left, Text Right → Primary*
 */
export interface VisualTextSplitSliceImageLeftTextRightPrimary {
  /**
   * Section Preheading field in *VisualTextSplit → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_text_split.image_left_text_right.primary.section_preheading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_preheading: prismic.RichTextField;

  /**
   * Section Heading field in *VisualTextSplit → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_text_split.image_left_text_right.primary.section_heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_heading: prismic.RichTextField;

  /**
   * Section Description field in *VisualTextSplit → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_text_split.image_left_text_right.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * Visual Block field in *VisualTextSplit → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_text_split.image_left_text_right.primary.visual_block
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  visual_block: prismic.ImageField<never>;

  /**
   * Visual Caption field in *VisualTextSplit → Image Left, Text Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_text_split.image_left_text_right.primary.visual_caption
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  visual_caption: prismic.RichTextField;
}

/**
 * Image Left, Text Right variation for VisualTextSplit Slice
 *
 * - **API ID**: `image_left_text_right`
 * - **Description**: Image or illustration block positioned left, textual content with heading and description on the right.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisualTextSplitSliceImageLeftTextRight =
  prismic.SharedSliceVariation<
    "image_left_text_right",
    Simplify<VisualTextSplitSliceImageLeftTextRightPrimary>,
    never
  >;

/**
 * Slice variation for *VisualTextSplit*
 */
type VisualTextSplitSliceVariation = VisualTextSplitSliceImageLeftTextRight;

/**
 * VisualTextSplit Shared Slice
 *
 * - **API ID**: `visual_text_split`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VisualTextSplitSlice = prismic.SharedSlice<
  "visual_text_split",
  VisualTextSplitSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      AllDocumentTypes,
      CoreTeamGridSlice,
      CoreTeamGridSliceDefaultPrimaryMembersItem,
      CoreTeamGridSliceDefaultPrimary,
      CoreTeamGridSliceVariation,
      CoreTeamGridSliceDefault,
      CtaHeroBannerSlice,
      CtaHeroBannerSliceDefaultPrimary,
      CtaHeroBannerSliceVariation,
      CtaHeroBannerSliceDefault,
      FeatureColumnsIntroSlice,
      FeatureColumnsIntroSliceHeadingText3ColumnFeaturePrimaryFeaturesItem,
      FeatureColumnsIntroSliceHeadingText3ColumnFeaturePrimary,
      FeatureColumnsIntroSliceVariation,
      FeatureColumnsIntroSliceHeadingText3ColumnFeature,
      FeaturedUpdatesSlice,
      FeaturedUpdatesSliceDefaultPrimaryUpdatesItem,
      FeaturedUpdatesSliceDefaultPrimary,
      FeaturedUpdatesSliceVariation,
      FeaturedUpdatesSliceDefault,
      HeaderNavigationSlice,
      HeaderNavigationSliceDefaultPrimaryNavLinksItem,
      HeaderNavigationSliceDefaultPrimary,
      HeaderNavigationSliceVariation,
      HeaderNavigationSliceDefault,
      HeadlineCtaImageSlice,
      HeadlineCtaImageSliceDefaultPrimary,
      HeadlineCtaImageSliceVariation,
      HeadlineCtaImageSliceDefault,
      HeadlineDescriptionGraphCtaSlice,
      HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimaryMetricsListItem,
      HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimaryTagListItem,
      HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetricPrimary,
      HeadlineDescriptionGraphCtaSliceVariation,
      HeadlineDescriptionGraphCtaSliceDefaultLeftTextRightMetric,
      IconBulletlistIntroSlice,
      IconBulletlistIntroSliceIntroWithIconBulletlistPrimaryItemsItem,
      IconBulletlistIntroSliceIntroWithIconBulletlistPrimary,
      IconBulletlistIntroSliceVariation,
      IconBulletlistIntroSliceIntroWithIconBulletlist,
      IconHeadlineColumnsSlice,
      IconHeadlineColumnsSliceDefaultPrimaryItemsItem,
      IconHeadlineColumnsSliceDefaultPrimary,
      IconHeadlineColumnsSliceVariation,
      IconHeadlineColumnsSliceDefault,
      MediaSideIntroSlice,
      MediaSideIntroSliceLogoLeftTextRightPrimary,
      MediaSideIntroSliceVariation,
      MediaSideIntroSliceLogoLeftTextRight,
      MilestoneHighlightsSlice,
      MilestoneHighlightsSliceDefaultPrimaryMilestonesItem,
      MilestoneHighlightsSliceDefaultPrimary,
      MilestoneHighlightsSliceVariation,
      MilestoneHighlightsSliceDefault,
      MilestoneTimelineSlice,
      MilestoneTimelineSliceSimpleTwoColumnPrimaryMilestonesItem,
      MilestoneTimelineSliceSimpleTwoColumnPrimary,
      MilestoneTimelineSliceVariation,
      MilestoneTimelineSliceSimpleTwoColumn,
      MultiColumnFooterSlice,
      MultiColumnFooterSliceStandardPrimaryColumnsItem,
      MultiColumnFooterSliceStandardPrimary,
      MultiColumnFooterSliceVariation,
      MultiColumnFooterSliceStandard,
      SideBySideFeatureListSlice,
      SideBySideFeatureListSliceDefaultPrimaryFeatureGroupsItem,
      SideBySideFeatureListSliceDefaultPrimary,
      SideBySideFeatureListSliceVariation,
      SideBySideFeatureListSliceDefault,
      TimelineGridSlice,
      TimelineGridSliceThreeColumnSimplePrimaryTimelineItemsItem,
      TimelineGridSliceThreeColumnSimplePrimary,
      TimelineGridSliceVariation,
      TimelineGridSliceThreeColumnSimple,
      TimelineHighlightsSlice,
      TimelineHighlightsSliceTwoColumnEventsPrimaryMilestonesItem,
      TimelineHighlightsSliceTwoColumnEventsPrimary,
      TimelineHighlightsSliceVariation,
      TimelineHighlightsSliceTwoColumnEvents,
      TwoColumnImageTextIntroSlice,
      TwoColumnImageTextIntroSliceImageLeftTextRightIntroPrimary,
      TwoColumnImageTextIntroSliceVariation,
      TwoColumnImageTextIntroSliceImageLeftTextRightIntro,
      VisualTextSplitSlice,
      VisualTextSplitSliceImageLeftTextRightPrimary,
      VisualTextSplitSliceVariation,
      VisualTextSplitSliceImageLeftTextRight,
    };
  }
}
