// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  core_team_grid: dynamic(() => import("./CoreTeamGrid")),
  cta_hero_banner: dynamic(() => import("./CtaHeroBanner")),
  feature_columns_intro: dynamic(() => import("./FeatureColumnsIntro")),
  featured_updates: dynamic(() => import("./FeaturedUpdates")),
  header_navigation: dynamic(() => import("./HeaderNavigation")),
  headline_cta_image: dynamic(() => import("./HeroBanner")),
  headline_description_graph_cta: dynamic(
    () => import("./HeadlineDescriptionGraphCta"),
  ),
  icon_bulletlist_intro: dynamic(() => import("./IconBulletlistIntro")),
  icon_headline_columns: dynamic(() => import("./IconHeadlineColumns")),
  media_side_intro: dynamic(() => import("./MediaSideIntro")),
  milestone_highlights: dynamic(() => import("./MilestoneHighlights")),
  milestone_timeline: dynamic(() => import("./MilestoneTimeline")),
  multi_column_footer: dynamic(() => import("./MultiColumnFooter")),
  side_by_side_feature_list: dynamic(() => import("./SideBySideFeatureList")),
  timeline_grid: dynamic(() => import("./TimelineGrid")),
  timeline_highlights: dynamic(() => import("./TimelineHighlights")),
  two_column_image_text_intro: dynamic(
    () => import("./TwoColumnImageTextIntro"),
  ),
  visual_text_split: dynamic(() => import("./VisualTextSplit")),
};
